# Generated by Django 3.0.4 on 2020-03-24 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departament_name', models.CharField(max_length=100, verbose_name='Департамент')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=100, verbose_name='Отдел')),
                ('departament',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Departament',
                                   verbose_name='Ссылка на id департамента')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Division',
                                               verbose_name='Ссылка на id отдела')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=15, verbose_name='Телефон')),
                ('email', models.CharField(default='', max_length=100, verbose_name='Email')),
                ('main_contact',
                 models.BooleanField(default=False, max_length=1, verbose_name='Признак главного контакта')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student',
                                              verbose_name='Ссылка на id сотрудника')),
            ],
        ),
    ]
