# Generated by Django 3.0.4 on 2020-04-01 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Департамент')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Отдел')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Departament',
                                              verbose_name='Департамент')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=30, verbose_name='Отчество')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Section',
                                              verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['last_name', 'first_name', 'second_name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('phone', 'Телефон'), ('email', 'E-mail')], max_length=5,
                                          verbose_name='Тип')),
                ('value', models.CharField(max_length=30, verbose_name='Значение')),
                ('primary', models.BooleanField(blank=True, default=False, verbose_name='Основной')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student',
                                              verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'unique_together': {('student', 'primary', 'type')},
            },
        ),
    ]
