# Generated by Django 2.2.2 on 2020-04-19 19:31

import apps.base.utils
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.CharField(default=apps.base.utils.custom_uuid, editable=False, max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('topic', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', related_query_name='course', to='courses.Course')),
            ],
            options={
                'db_table': 'lectures',
            },
        ),
    ]
